algoritmo "Atividade17"


var
contador, impar, par, maior, menor: inteiro

inicio
para contador de 1 ate 20 faca
se contador mod 2=0 entao
escreva(contador,"=par")
escreval()
senao
escreval()
se contador <> entao
escreva(contador,"=impar |")
fimse
fimse
fimpara
escreval()
escreval()
escreval("números menores que 7")
para contador de 1 ate 20 faca
se contador >= 50 entao
escreva(contador)
senao
se contador <7 entao
escreva(contador,"<7")
fimse
fimse
fimpara



fimalgoritmo